<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 3 Análisis Exploratorio de Datos (EDA) | Proyecto final: Métodos Estadísticos</title>
  <meta name="description" content="Informe y Análisis Estadístico Final del Curso de Métodos Estadísticos." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 3 Análisis Exploratorio de Datos (EDA) | Proyecto final: Métodos Estadísticos" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Informe y Análisis Estadístico Final del Curso de Métodos Estadísticos." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 3 Análisis Exploratorio de Datos (EDA) | Proyecto final: Métodos Estadísticos" />
  
  <meta name="twitter:description" content="Informe y Análisis Estadístico Final del Curso de Métodos Estadísticos." />
  

<meta name="author" content="Camilo Padilla &amp; Juan Campo" />


<meta name="date" content="2026-09-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Proyecto Final - Métodos Estadísticos</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Presentación</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#estructura-del-documento"><i class="fa fa-check"></i><b>1.1</b> Estructura del Documento</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introducción y Objetivos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#contexto"><i class="fa fa-check"></i><b>2.1</b> Contexto</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#problem%C3%A1tica"><i class="fa fa-check"></i><b>2.2</b> Problemática</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#objetivos-del-proyecto"><i class="fa fa-check"></i><b>2.3</b> Objetivos del Proyecto</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="intro.html"><a href="intro.html#objetivo-general"><i class="fa fa-check"></i><b>2.3.1</b> Objetivo general</a></li>
<li class="chapter" data-level="2.3.2" data-path="intro.html"><a href="intro.html#objetivos-especificos"><i class="fa fa-check"></i><b>2.3.2</b> Objetivos especificos</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#justificaci%C3%B3n"><i class="fa fa-check"></i><b>2.4</b> Justificación</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="eda.html"><a href="eda.html"><i class="fa fa-check"></i><b>3</b> Análisis Exploratorio de Datos (EDA)</a>
<ul>
<li class="chapter" data-level="3.1" data-path="eda.html"><a href="eda.html#dataset-y-ficha-tecnica"><i class="fa fa-check"></i><b>3.1</b> Dataset y ficha tecnica</a></li>
<li class="chapter" data-level="3.2" data-path="eda.html"><a href="eda.html#importamos-librerias"><i class="fa fa-check"></i><b>3.2</b> Importamos librerias</a></li>
<li class="chapter" data-level="3.3" data-path="eda.html"><a href="eda.html#carga-de-datos"><i class="fa fa-check"></i><b>3.3</b> Carga de Datos</a></li>
<li class="chapter" data-level="3.4" data-path="eda.html"><a href="eda.html#diccionario-de-variables"><i class="fa fa-check"></i><b>3.4</b> Diccionario de Variables</a></li>
<li class="chapter" data-level="3.5" data-path="eda.html"><a href="eda.html#exploraci%C3%B3n-del-data-set."><i class="fa fa-check"></i><b>3.5</b> Exploración del data set.</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="eda.html"><a href="eda.html#exploraci%C3%B3n-de-la-variable-de-respuesta"><i class="fa fa-check"></i><b>3.5.1</b> Exploración de la variable de respuesta</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="eda.html"><a href="eda.html#exploracion-de-las-varibles-independientes"><i class="fa fa-check"></i><b>3.6</b> Exploracion de las varibles independientes</a></li>
<li class="chapter" data-level="3.7" data-path="eda.html"><a href="eda.html#anlisis-univariado-de-las-variables"><i class="fa fa-check"></i><b>3.7</b> Anlisis Univariado de las variables</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="eda.html"><a href="eda.html#analisis-boxplot-tiempo-de-curado"><i class="fa fa-check"></i><b>3.7.1</b> Analisis boxplot tiempo de curado</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="eda.html"><a href="eda.html#an%C3%A1lisis-bivariado-relaci%C3%B3n-con-la-resistencia-del-concreto"><i class="fa fa-check"></i><b>3.8</b> Análisis bivariado: relación con la resistencia del concreto</a></li>
<li class="chapter" data-level="3.9" data-path="eda.html"><a href="eda.html#an%C3%A1lisis-multivariado"><i class="fa fa-check"></i><b>3.9</b> Análisis multivariado</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con Bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Proyecto final: Métodos Estadísticos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="eda" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Capítulo 3</span> Análisis Exploratorio de Datos (EDA)<a href="eda.html#eda" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En este capítulo analizamos las variables cuantitativas del dataset de Concrete Compressive Strength (Resistencia del Concreto).</p>
<div id="dataset-y-ficha-tecnica" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Dataset y ficha tecnica<a href="eda.html#dataset-y-ficha-tecnica" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p><strong>Fuente:</strong> UCI Machine Learning Repository (Donado por el Prof. I-Cheng Yeh, 2007).</p></li>
<li><p><strong>Área:</strong> Ingeniería Civil / Ciencia de Materiales.</p></li>
<li><p><strong>Número de Observaciones (</strong>N<strong>):</strong> 1,030 mezclas experimentales.</p></li>
<li><p><strong>Número de Variables:</strong> 9 variables cuantitativas (8 independientes + 1 dependiente).</p></li>
<li><p><strong>Valores Faltantes:</strong> Ninguno.</p></li>
</ul>
</div>
<div id="importamos-librerias" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Importamos librerias<a href="eda.html#importamos-librerias" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="eda.html#cb1-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="eda.html#cb1-2" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="eda.html#cb1-3" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb1-4"><a href="eda.html#cb1-4" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-5"><a href="eda.html#cb1-5" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb1-6"><a href="eda.html#cb1-6" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-7"><a href="eda.html#cb1-7" tabindex="-1"></a><span class="fu">library</span>(effsize)</span>
<span id="cb1-8"><a href="eda.html#cb1-8" tabindex="-1"></a><span class="fu">library</span>(rstatix)</span></code></pre></div>
</div>
<div id="carga-de-datos" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Carga de Datos<a href="eda.html#carga-de-datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="eda.html#cb2-1" tabindex="-1"></a>Concrete_Data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;concrete+compressive+strength/Concrete_Data.xls&quot;</span>)</span>
<span id="cb2-2"><a href="eda.html#cb2-2" tabindex="-1"></a><span class="co"># View(Concrete_Data)</span></span>
<span id="cb2-3"><a href="eda.html#cb2-3" tabindex="-1"></a></span>
<span id="cb2-4"><a href="eda.html#cb2-4" tabindex="-1"></a>df <span class="ot">&lt;-</span> Concrete_Data</span></code></pre></div>
</div>
<div id="diccionario-de-variables" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Diccionario de Variables<a href="eda.html#diccionario-de-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Aclaramos que cada observacion representa un ensayo de laboratorio con una receta individual con ingredientes mezclados para hacer un metro cubico de cemento, el tiempo que se dejo reposar y la fuerza que resistio.</p>
<p>Todas las variables son cuantitativas continuas:</p>
<table>
<colgroup>
<col width="20%" />
<col width="20%" />
<col width="20%" />
<col width="20%" />
<col width="20%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Variable</th>
<th align="left">Nombre en Dataset</th>
<th align="left">Tipo</th>
<th align="left">Unidad</th>
<th align="left">Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><strong>1. Cemento</strong></td>
<td align="left"><code>Cement</code></td>
<td align="left">Entrada (Indep.)</td>
<td align="left"><span class="math inline">\(\text{kg/m}^3\)</span></td>
<td align="left">Componente aglutinante principal.</td>
</tr>
<tr class="even">
<td align="left"><strong>2. Escoria de alto horno</strong></td>
<td align="left"><code>Blast_Furnace_Slag</code></td>
<td align="left">Entrada (Indep.)</td>
<td align="left"><span class="math inline">\(\text{kg/m}^3\)</span></td>
<td align="left">Subproducto siderúrgico que mejora durabilidad.</td>
</tr>
<tr class="odd">
<td align="left"><strong>3. Ceniza volante</strong></td>
<td align="left"><code>Fly_Ash</code></td>
<td align="left">Entrada (Indep.)</td>
<td align="left"><span class="math inline">\(\text{kg/m}^3\)</span></td>
<td align="left">Subproducto de centrales térmicas.</td>
</tr>
<tr class="even">
<td align="left"><strong>4. Agua</strong></td>
<td align="left"><code>Water</code></td>
<td align="left">Entrada (Indep.)</td>
<td align="left"><span class="math inline">\(\text{kg/m}^3\)</span></td>
<td align="left">Cantidad de agua.</td>
</tr>
<tr class="odd">
<td align="left"><strong>5. Superplastificante</strong></td>
<td align="left"><code>Superplasticizer</code></td>
<td align="left">Entrada (Indep.)</td>
<td align="left"><span class="math inline">\(\text{kg/m}^3\)</span></td>
<td align="left">Aditivo químico que reduce necesidad de agua.</td>
</tr>
<tr class="even">
<td align="left"><strong>6. Agregado Grueso</strong></td>
<td align="left"><code>Coarse_Aggregate</code></td>
<td align="left">Entrada (Indep.)</td>
<td align="left"><span class="math inline">\(\text{kg/m}^3\)</span></td>
<td align="left">Grava / Piedra chancada.</td>
</tr>
<tr class="odd">
<td align="left"><strong>7. Agregado Fino</strong></td>
<td align="left"><code>Fine_Aggregate</code></td>
<td align="left">Entrada (Indep.)</td>
<td align="left"><span class="math inline">\(\text{kg/m}^3\)</span></td>
<td align="left">Arena.</td>
</tr>
<tr class="even">
<td align="left"><strong>8. Edad</strong></td>
<td align="left"><code>Age</code></td>
<td align="left">Entrada (Indep.)</td>
<td align="left">Días (<span class="math inline">\(1 \text{ a } 365\)</span>)</td>
<td align="left">Tiempo de maduración/curado del concreto.</td>
</tr>
<tr class="odd">
<td align="left"><strong>9. Resistencia</strong></td>
<td align="left"><code>Concrete_Compressive_Strength</code></td>
<td align="left"><strong>Salida (Dependiente)</strong></td>
<td align="left"><span class="math inline">\(\text{MPa}\)</span></td>
<td align="left">Resistencia final a la compresión.</td>
</tr>
</tbody>
</table>
</div>
<div id="exploración-del-data-set." class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Exploración del data set.<a href="eda.html#exploraci%C3%B3n-del-data-set." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Resumimos los nombres de las variables</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="eda.html#cb3-1" tabindex="-1"></a>df_clean <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="eda.html#cb3-2" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb3-3"><a href="eda.html#cb3-3" tabindex="-1"></a>    <span class="at">cemento          =</span> <span class="st">`</span><span class="at">Cement (component 1)(kg in a m^3 mixture)</span><span class="st">`</span>,</span>
<span id="cb3-4"><a href="eda.html#cb3-4" tabindex="-1"></a>    <span class="at">escoria          =</span> <span class="st">`</span><span class="at">Blast Furnace Slag (component 2)(kg in a m^3 mixture)</span><span class="st">`</span>,</span>
<span id="cb3-5"><a href="eda.html#cb3-5" tabindex="-1"></a>    <span class="at">ceniza           =</span> <span class="st">`</span><span class="at">Fly Ash (component 3)(kg in a m^3 mixture)</span><span class="st">`</span>,</span>
<span id="cb3-6"><a href="eda.html#cb3-6" tabindex="-1"></a>    <span class="at">agua             =</span> <span class="st">`</span><span class="at">Water  (component 4)(kg in a m^3 mixture)</span><span class="st">`</span>,</span>
<span id="cb3-7"><a href="eda.html#cb3-7" tabindex="-1"></a>    <span class="at">superplast       =</span> <span class="st">`</span><span class="at">Superplasticizer (component 5)(kg in a m^3 mixture)</span><span class="st">`</span>,</span>
<span id="cb3-8"><a href="eda.html#cb3-8" tabindex="-1"></a>    <span class="at">agregado_grueso  =</span> <span class="st">`</span><span class="at">Coarse Aggregate  (component 6)(kg in a m^3 mixture)</span><span class="st">`</span>,</span>
<span id="cb3-9"><a href="eda.html#cb3-9" tabindex="-1"></a>    <span class="at">agregado_fino    =</span> <span class="st">`</span><span class="at">Fine Aggregate (component 7)(kg in a m^3 mixture)</span><span class="st">`</span>,</span>
<span id="cb3-10"><a href="eda.html#cb3-10" tabindex="-1"></a>    <span class="at">edad             =</span> <span class="st">`</span><span class="at">Age (day)</span><span class="st">`</span>,</span>
<span id="cb3-11"><a href="eda.html#cb3-11" tabindex="-1"></a>    <span class="at">resistencia      =</span> <span class="st">`</span><span class="at">Concrete compressive strength(MPa, megapascals)</span><span class="st">`</span></span>
<span id="cb3-12"><a href="eda.html#cb3-12" tabindex="-1"></a>  )</span></code></pre></div>
<div id="exploración-de-la-variable-de-respuesta" class="section level3 hasAnchor" number="3.5.1">
<h3><span class="header-section-number">3.5.1</span> Exploración de la variable de respuesta<a href="eda.html#exploraci%C3%B3n-de-la-variable-de-respuesta" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="eda.html#cb4-1" tabindex="-1"></a>df_clean <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(</span>
<span id="cb4-2"><a href="eda.html#cb4-2" tabindex="-1"></a>  <span class="at">n =</span> <span class="fu">length</span>(resistencia),</span>
<span id="cb4-3"><a href="eda.html#cb4-3" tabindex="-1"></a>  <span class="at">media =</span> <span class="fu">mean</span>(resistencia),</span>
<span id="cb4-4"><a href="eda.html#cb4-4" tabindex="-1"></a>  <span class="at">sd =</span> <span class="fu">sd</span>(resistencia),</span>
<span id="cb4-5"><a href="eda.html#cb4-5" tabindex="-1"></a>  <span class="at">mediana =</span> <span class="fu">median</span>(resistencia),</span>
<span id="cb4-6"><a href="eda.html#cb4-6" tabindex="-1"></a>  <span class="at">RIC =</span> <span class="fu">IQR</span>(resistencia),</span>
<span id="cb4-7"><a href="eda.html#cb4-7" tabindex="-1"></a>  <span class="at">Q1 =</span> <span class="fu">quantile</span>(resistencia, <span class="fl">0.25</span>),</span>
<span id="cb4-8"><a href="eda.html#cb4-8" tabindex="-1"></a>  <span class="at">Q3 =</span> <span class="fu">quantile</span>(resistencia, <span class="fl">0.75</span>),</span>
<span id="cb4-9"><a href="eda.html#cb4-9" tabindex="-1"></a>  <span class="at">minimo =</span> <span class="fu">min</span>(resistencia),</span>
<span id="cb4-10"><a href="eda.html#cb4-10" tabindex="-1"></a>  <span class="at">maximo =</span> <span class="fu">max</span>(resistencia),</span>
<span id="cb4-11"><a href="eda.html#cb4-11" tabindex="-1"></a>  <span class="at">asim =</span> <span class="fu">skewness</span>(resistencia),</span>
<span id="cb4-12"><a href="eda.html#cb4-12" tabindex="-1"></a>  <span class="at">curtosis =</span> <span class="fu">kurtosis</span>(resistencia)</span>
<span id="cb4-13"><a href="eda.html#cb4-13" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 11
##       n media    sd mediana   RIC    Q1    Q3 minimo maximo  asim curtosis
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
## 1  1030  35.8  16.7    34.4  22.4  23.7  46.1   2.33   82.6 0.416     2.68</code></pre>
<p>Vemos que las 1030 observaciones de mezclas de concreto, tienen una resistencia de comprension de 35.817 MPa, con una desviación estándar de 16.70 MPa. Además, el 50% de las mezclas tienen una resistencia igual o menor a 34.442 MPa. Además, se observa una mezcla de concreto experimental con resistencia de 85.59 MPa siendo esta la observación con mayor Resistencia final a la compresión y otras con la minima resistencia entre las observaciones con 2.33 MPa.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="eda.html#cb6-1" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>)</span>
<span id="cb6-2"><a href="eda.html#cb6-2" tabindex="-1"></a>df_clean <span class="sc">|&gt;</span></span>
<span id="cb6-3"><a href="eda.html#cb6-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> resistencia)) <span class="sc">+</span></span>
<span id="cb6-4"><a href="eda.html#cb6-4" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb6-5"><a href="eda.html#cb6-5" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb6-6"><a href="eda.html#cb6-6" tabindex="-1"></a>    <span class="at">binwidth =</span> <span class="dv">2</span>,</span>
<span id="cb6-7"><a href="eda.html#cb6-7" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;darkblue&quot;</span>,</span>
<span id="cb6-8"><a href="eda.html#cb6-8" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;white&quot;</span>,</span>
<span id="cb6-9"><a href="eda.html#cb6-9" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.6</span></span>
<span id="cb6-10"><a href="eda.html#cb6-10" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb6-11"><a href="eda.html#cb6-11" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;darkblue&quot;</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb6-12"><a href="eda.html#cb6-12" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb6-13"><a href="eda.html#cb6-13" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución de la resistencia del concreto&quot;</span>,</span>
<span id="cb6-14"><a href="eda.html#cb6-14" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Resistencia&quot;</span>,</span>
<span id="cb6-15"><a href="eda.html#cb6-15" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Densidad&quot;</span></span>
<span id="cb6-16"><a href="eda.html#cb6-16" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb6-17"><a href="eda.html#cb6-17" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-3-1.png" alt="" width="672" style="display: block; margin: auto;" />
la resistencia muestra una distribución con forma parecida a una <strong>simétrica con forma de campana</strong>, centrada en torno a los <span class="math inline">\(35\text{ MPa}\)</span> y abarcando un rango desde los <span class="math inline">\(2.3\)</span> hasta los <span class="math inline">\(82.6\text{ MPa}\)</span>. La curva de densidad sugiere un comportamiento cercano a la <strong>distribución normal</strong>, reflejando una muestra equilibrada que abarca desde concretos convencionales hasta mezclas de alto rendimiento.</p>
</div>
</div>
<div id="exploracion-de-las-varibles-independientes" class="section level2 hasAnchor" number="3.6">
<h2><span class="header-section-number">3.6</span> Exploracion de las varibles independientes<a href="eda.html#exploracion-de-las-varibles-independientes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Creamos la siguiente tabla para observar de forma descriptiva las variables independientes que analizaremos y asi complementar el analisis de los boxplots con ella.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="eda.html#cb7-1" tabindex="-1"></a>tabla_independientes <span class="ot">&lt;-</span> df_clean <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="eda.html#cb7-2" tabindex="-1"></a>  <span class="fu">select</span>(cemento, ceniza, agua, edad) <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="eda.html#cb7-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb7-4"><a href="eda.html#cb7-4" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb7-5"><a href="eda.html#cb7-5" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">&quot;variables&quot;</span>,</span>
<span id="cb7-6"><a href="eda.html#cb7-6" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">&quot;valor&quot;</span></span>
<span id="cb7-7"><a href="eda.html#cb7-7" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb7-8"><a href="eda.html#cb7-8" tabindex="-1"></a>  <span class="fu">group_by</span>(variables) <span class="sc">|&gt;</span></span>
<span id="cb7-9"><a href="eda.html#cb7-9" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb7-10"><a href="eda.html#cb7-10" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(valor),</span>
<span id="cb7-11"><a href="eda.html#cb7-11" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">round</span>(<span class="fu">mean</span>(valor), <span class="dv">3</span>),</span>
<span id="cb7-12"><a href="eda.html#cb7-12" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">round</span>(<span class="fu">sd</span>(valor), <span class="dv">3</span>),</span>
<span id="cb7-13"><a href="eda.html#cb7-13" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">round</span>(<span class="fu">median</span>(valor), <span class="dv">3</span>),</span>
<span id="cb7-14"><a href="eda.html#cb7-14" tabindex="-1"></a>    <span class="at">RIC =</span> <span class="fu">round</span>(<span class="fu">IQR</span>(valor), <span class="dv">3</span>),</span>
<span id="cb7-15"><a href="eda.html#cb7-15" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">round</span>(<span class="fu">quantile</span>(valor, <span class="fl">0.25</span>), <span class="dv">3</span>),</span>
<span id="cb7-16"><a href="eda.html#cb7-16" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">round</span>(<span class="fu">quantile</span>(valor, <span class="fl">0.75</span>), <span class="dv">3</span>),</span>
<span id="cb7-17"><a href="eda.html#cb7-17" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">round</span>(<span class="fu">min</span>(valor), <span class="dv">3</span>),</span>
<span id="cb7-18"><a href="eda.html#cb7-18" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">round</span>(<span class="fu">max</span>(valor), <span class="dv">3</span>),</span>
<span id="cb7-19"><a href="eda.html#cb7-19" tabindex="-1"></a>    <span class="at">asim =</span> <span class="fu">round</span>(<span class="fu">skewness</span>(valor), <span class="dv">3</span>),</span>
<span id="cb7-20"><a href="eda.html#cb7-20" tabindex="-1"></a>    <span class="at">curtosis =</span> <span class="fu">round</span>(<span class="fu">kurtosis</span>(valor), <span class="dv">3</span>)</span>
<span id="cb7-21"><a href="eda.html#cb7-21" tabindex="-1"></a>  )</span>
<span id="cb7-22"><a href="eda.html#cb7-22" tabindex="-1"></a></span>
<span id="cb7-23"><a href="eda.html#cb7-23" tabindex="-1"></a>tabla_independientes</span></code></pre></div>
<pre><code>## # A tibble: 4 × 12
##   variables     n media    sd mediana   RIC    Q1    Q3 minimo maximo  asim
##   &lt;chr&gt;     &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1 agua       1030 182.   21.4    185   27.1  165.  192    122.   247  0.074
## 2 cemento    1030 281.  105.     273. 158.   192.  350    102    540  0.509
## 3 ceniza     1030  54.2  64.0      0  118.     0   118.     0    200. 0.537
## 4 edad       1030  45.7  63.2     28   49      7    56      1    365  3.26 
## # ℹ 1 more variable: curtosis &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="eda.html#cb9-1" tabindex="-1"></a>df_clean <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="eda.html#cb9-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ceniza)) <span class="sc">+</span></span>
<span id="cb9-3"><a href="eda.html#cb9-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb9-4"><a href="eda.html#cb9-4" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb9-5"><a href="eda.html#cb9-5" tabindex="-1"></a>    <span class="at">binwidth =</span> <span class="dv">10</span>, <span class="co"># Intervalos de 10 kg/m^3</span></span>
<span id="cb9-6"><a href="eda.html#cb9-6" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;#d95f02&quot;</span>, <span class="co"># Tono naranja / teja</span></span>
<span id="cb9-7"><a href="eda.html#cb9-7" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;white&quot;</span>,</span>
<span id="cb9-8"><a href="eda.html#cb9-8" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.6</span></span>
<span id="cb9-9"><a href="eda.html#cb9-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-10"><a href="eda.html#cb9-10" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;#d95f02&quot;</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb9-11"><a href="eda.html#cb9-11" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-12"><a href="eda.html#cb9-12" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución del contenido de Ceniza Volante&quot;</span>,</span>
<span id="cb9-13"><a href="eda.html#cb9-13" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Ceniza Volante (kg/m³)&quot;</span>,</span>
<span id="cb9-14"><a href="eda.html#cb9-14" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Densidad&quot;</span></span>
<span id="cb9-15"><a href="eda.html#cb9-15" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-16"><a href="eda.html#cb9-16" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-4-1.png" alt="" width="672" style="display: block; margin: auto;" />
La distribución es fuertemente bimodal e inflada en ceros. Presenta una concentración masiva en los <span class="math inline">\(0\text{ kg/m}^3\)</span> correspondiente a las mezclas tradicionales de control (<span class="math inline">\(55\%\)</span> de la muestra), seguida de un segundo agrupamiento entre los <span class="math inline">\(80\)</span> y <span class="math inline">\(160\text{ kg/m}^3\)</span> en aquellas formulaciones donde sí se sustituyó cemento por ceniza. Esta notable asimetría y falta de continuidad confirma la <strong>no normalidad</strong> de la variable.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="eda.html#cb10-1" tabindex="-1"></a>df_clean <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="eda.html#cb10-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> edad)) <span class="sc">+</span></span>
<span id="cb10-3"><a href="eda.html#cb10-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb10-4"><a href="eda.html#cb10-4" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb10-5"><a href="eda.html#cb10-5" tabindex="-1"></a>    <span class="at">binwidth =</span> <span class="dv">14</span>, <span class="co"># Intervalos de 14 días (2 semanas)</span></span>
<span id="cb10-6"><a href="eda.html#cb10-6" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">&quot;#7570b3&quot;</span>, <span class="co"># Tono violeta</span></span>
<span id="cb10-7"><a href="eda.html#cb10-7" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;white&quot;</span>,</span>
<span id="cb10-8"><a href="eda.html#cb10-8" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.6</span></span>
<span id="cb10-9"><a href="eda.html#cb10-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb10-10"><a href="eda.html#cb10-10" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;#7570b3&quot;</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb10-11"><a href="eda.html#cb10-11" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb10-12"><a href="eda.html#cb10-12" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución del Tiempo de Curado&quot;</span>,</span>
<span id="cb10-13"><a href="eda.html#cb10-13" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Tiempo de Curado (Días)&quot;</span>,</span>
<span id="cb10-14"><a href="eda.html#cb10-14" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Densidad&quot;</span></span>
<span id="cb10-15"><a href="eda.html#cb10-15" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb10-16"><a href="eda.html#cb10-16" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-5-1.png" alt="" width="672" style="display: block; margin: auto;" />
La distribución exhibe un marcado sesgo positivo con picos, concentrando la gran mayoría de las observaciones en los <span class="math inline">\(28\text{ días}\)</span> la cual es la edad estándar de diseño y en periodos tempranos (<span class="math inline">\(\le 7\text{ días}\)</span>). La densidad decae drásticamente a partir de los <span class="math inline">\(56\text{ días}\)</span>, extendiéndose en una cola larga hasta los <span class="math inline">\(365\text{ días}\)</span>, lo cual evidencia una distribución <strong>no normal</strong> explicada por el diseño experimental enfocado en etapas normativas de obra.</p>
</div>
<div id="anlisis-univariado-de-las-variables" class="section level2 hasAnchor" number="3.7">
<h2><span class="header-section-number">3.7</span> Anlisis Univariado de las variables<a href="eda.html#anlisis-univariado-de-las-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="eda.html#cb11-1" tabindex="-1"></a><span class="co"># 1. Boxplot de Ceniza Volante</span></span>
<span id="cb11-2"><a href="eda.html#cb11-2" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="eda.html#cb11-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">Fly Ash (component 3)(kg in a m^3 mixture)</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb11-4"><a href="eda.html#cb11-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb11-5"><a href="eda.html#cb11-5" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-6"><a href="eda.html#cb11-6" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Ceniza Volante (Fly Ash)&quot;</span>,</span>
<span id="cb11-7"><a href="eda.html#cb11-7" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Ceniza Volante (kg/m³)&quot;</span>,</span>
<span id="cb11-8"><a href="eda.html#cb11-8" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb11-9"><a href="eda.html#cb11-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-10"><a href="eda.html#cb11-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb11-11"><a href="eda.html#cb11-11" tabindex="-1"></a></span>
<span id="cb11-12"><a href="eda.html#cb11-12" tabindex="-1"></a></span>
<span id="cb11-13"><a href="eda.html#cb11-13" tabindex="-1"></a><span class="co"># 2. Boxplot de Edad de Curado</span></span>
<span id="cb11-14"><a href="eda.html#cb11-14" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb11-15"><a href="eda.html#cb11-15" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">Age (day)</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb11-16"><a href="eda.html#cb11-16" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb11-17"><a href="eda.html#cb11-17" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-18"><a href="eda.html#cb11-18" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Tiempo de Curado&quot;</span>,</span>
<span id="cb11-19"><a href="eda.html#cb11-19" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Edad (Días)&quot;</span>,</span>
<span id="cb11-20"><a href="eda.html#cb11-20" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb11-21"><a href="eda.html#cb11-21" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-22"><a href="eda.html#cb11-22" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb11-23"><a href="eda.html#cb11-23" tabindex="-1"></a></span>
<span id="cb11-24"><a href="eda.html#cb11-24" tabindex="-1"></a><span class="co"># Boxplot de Cemento</span></span>
<span id="cb11-25"><a href="eda.html#cb11-25" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb11-26"><a href="eda.html#cb11-26" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">Cement (component 1)(kg in a m^3 mixture)</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb11-27"><a href="eda.html#cb11-27" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb11-28"><a href="eda.html#cb11-28" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-29"><a href="eda.html#cb11-29" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Cemento&quot;</span>,</span>
<span id="cb11-30"><a href="eda.html#cb11-30" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Cemento kg/m^3&quot;</span>,</span>
<span id="cb11-31"><a href="eda.html#cb11-31" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb11-32"><a href="eda.html#cb11-32" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-33"><a href="eda.html#cb11-33" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb11-34"><a href="eda.html#cb11-34" tabindex="-1"></a></span>
<span id="cb11-35"><a href="eda.html#cb11-35" tabindex="-1"></a></span>
<span id="cb11-36"><a href="eda.html#cb11-36" tabindex="-1"></a><span class="co"># 3. Boxplot de Resistencia a la Compresión -&gt; variable de respuest.</span></span>
<span id="cb11-37"><a href="eda.html#cb11-37" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb11-38"><a href="eda.html#cb11-38" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">Concrete compressive strength(MPa, megapascals)</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb11-39"><a href="eda.html#cb11-39" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb11-40"><a href="eda.html#cb11-40" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-41"><a href="eda.html#cb11-41" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Resistencia a la Compresión&quot;</span>,</span>
<span id="cb11-42"><a href="eda.html#cb11-42" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Resistencia (MPa)&quot;</span>,</span>
<span id="cb11-43"><a href="eda.html#cb11-43" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb11-44"><a href="eda.html#cb11-44" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-45"><a href="eda.html#cb11-45" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb11-46"><a href="eda.html#cb11-46" tabindex="-1"></a></span>
<span id="cb11-47"><a href="eda.html#cb11-47" tabindex="-1"></a><span class="co"># Boxplot de agua</span></span>
<span id="cb11-48"><a href="eda.html#cb11-48" tabindex="-1"></a>p5 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb11-49"><a href="eda.html#cb11-49" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">Water  (component 4)(kg in a m^3 mixture)</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb11-50"><a href="eda.html#cb11-50" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;skyblue&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb11-51"><a href="eda.html#cb11-51" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-52"><a href="eda.html#cb11-52" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Agua&quot;</span>,</span>
<span id="cb11-53"><a href="eda.html#cb11-53" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Agua Kg/m^3&quot;</span>,</span>
<span id="cb11-54"><a href="eda.html#cb11-54" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb11-55"><a href="eda.html#cb11-55" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-56"><a href="eda.html#cb11-56" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="eda.html#cb12-1" tabindex="-1"></a>p3</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-6-1.png" alt="" width="672" style="display: block; margin: auto;" />
Para la variable independiente “Cemento”, se observa un comportamiento homogéneo y balanceado, sin valores atipicos, con un promedio de cemento en la mezcla de <span class="math inline">\(281\text{ }kg/m^3\)</span> y una desviación estándar de <span class="math inline">\(104.507\text{ }kg/m^3\)</span>.</p>
<p>El diagrama de cjas y bigotes nos indica que el 50% de las observaciones de mezclas de concreto tienen un cantidad de cemento menor o igual a <span class="math inline">\(272.9\text{ }kg/m^3\)</span>, mostrando una <strong>cercanía con el promedio</strong>. En cuanto al rango intercuartílico, el <span class="math inline">\(25\%\)</span> de las mezclas con menor cantidad de cemento añadido registran valores iguales o inferiores a <span class="math inline">\(192.3\text{ }kg/m^3\)</span>, mientras que el <span class="math inline">\(75\%\)</span> de las muestras se sitúan por debajo de los <span class="math inline">\(350\text{ }kg/m^3\)</span>. Los bigotes abarcan un rango que va desde un mínimo de <span class="math inline">\(102\text{ }kg/m^3\)</span> hasta un maximo de cemento añadido de <span class="math inline">\(540\text{ }kg/m^3\)</span>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="eda.html#cb13-1" tabindex="-1"></a>p5</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/agua-1.png" alt="" width="672" style="display: block; margin: auto;" />
Para la variable agua, se observa un comportamiento homogéneo y balanceado, con un promedio de agua en la mezcla de <span class="math inline">\(181.5\text{ }kg/m^3\)</span> y una desviación estándar de <span class="math inline">\(21.3\text{ }kg/m^3\)</span>.</p>
<p>El 50% de las observaciones tienen la cantidad de agua añadida menor o igual a <span class="math inline">\(185\text{ }kg/m^3\)</span>, mostrando una <strong>notable cercanía con el promedio de agua añadida a las mezclas de concreto (<span class="math inline">\(181.5\text{ }kg/m^3\)</span>)</strong>. En cuanto al rango intercuartílico, el <span class="math inline">\(25\%\)</span> de las mezclas con menor cantidad de agua registran valores iguales o inferiores a <span class="math inline">\(164.9.37\text{ }kg/m^3\)</span>, mientras que el <span class="math inline">\(75\%\)</span> de las muestras se sitúan por debajo de los <span class="math inline">\(192\text{ }kg/m^3\)</span>. Los bigotes abarcan un rango que va desde un mínimo de <span class="math inline">\(121.74\text{ }kg/m^3\)</span> (concreto con mucha agua añadida, aumentando asi la sequedad de este) hasta aproximadamente los <span class="math inline">\(228\text{ }kg/m^3\)</span>. Se aprecian únicamente unos pocos <strong>valores atípicos superiores</strong> que alcanzan un máximo de <span class="math inline">\(247\text{ }kg/m^3\)</span>.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="eda.html#cb14-1" tabindex="-1"></a>p1</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-7-1.png" alt="" width="672" style="display: block; margin: auto;" />
### Analisis boxplot Fly Ash</p>
<p>Se observa una distribución atipica con alta dispersión de los datos, además por la tabla anterior la media del uso de ceniza en las mezclas es <span class="math inline">\(54.2 kg/m^3\)</span> y una desviación estándar de <span class="math inline">\(64 kg/m^3\)</span></p>
<p>Sin embargo el diagrama de caja muestra que el 50% de los valores de ceniza coincide con el limite inferior, esto indica que el 50% de las mezclas no contienen contienen ceniza volante. Por otra parte, el 75% de las observaciones contienen una cantidad de ceniza menor o igual a <span class="math inline">\(118.6 kg/m^3\)</span>, mientras que el migote señala mezclas con un maximo de <span class="math inline">\(201.1 kg/m^3\)</span>, no se evidencia ningun valor atipico.</p>
<p>¿porque hay este comportamiento de los datos centrado en cero?
esto se debe a que el conjunto de datos contiene mezclas de control convencionales elaboradas exclusivamente con cemento tradicional para servir de base comparativa. Por ende, la ceniza volante actúa como un componente opcional.</p>
<div id="analisis-boxplot-tiempo-de-curado" class="section level3 hasAnchor" number="3.7.1">
<h3><span class="header-section-number">3.7.1</span> Analisis boxplot tiempo de curado<a href="eda.html#analisis-boxplot-tiempo-de-curado" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="eda.html#cb15-1" tabindex="-1"></a>p2</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-8-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>La variable <span class="math inline">\(\text{Age}\)</span> (días de curado) presenta una concentración en edades tempranas y unagran dispersión, reflejada en un tiempo promedio de curado de <span class="math inline">\(45.7\text{ días}\)</span> y una desviación estándar de <span class="math inline">\(63.2\text{ días}\)</span>.</p>
<p>El boxplot nos permite observar una distribución sesgada a la derecha, tambien el <span class="math inline">\(50\%\)</span> de las muestras fueron ensayadas a los <span class="math inline">\(28\text{ días}\)</span> o menos, el <span class="math inline">\(25\%\)</span> inferior corresponde a edades tempranas iguales o menores a <span class="math inline">\(7\text{ días}\)</span>, y el <span class="math inline">\(75\%\)</span> central se concentra por debajo de los <span class="math inline">\(56\text{ días}\)</span>. No obstante, el diagrama de caja evidencia una serie de <strong>valores extremos</strong> en la parte superior, con esayos a los <span class="math inline">\(90\)</span>, <span class="math inline">\(180\)</span>, <span class="math inline">\(270\)</span> y hasta un máximo de <span class="math inline">\(365\text{ días}\)</span> es decir un año completo de curado.</p>
<p><strong>¿Por qué existen valores atípicos tan elevados?</strong><br />
En la práctica de la ingeniería civil, los ensayos estándar de control de calidad se realizan de forma rutinaria a los <span class="math inline">\(7\)</span>, <span class="math inline">\(14\)</span> y principalmente a los <span class="math inline">\(28\text{ días}\)</span>. Los tiempos de curado prolongados (<span class="math inline">\(&gt; 90\text{ días}\)</span>) son ensayos de investigación concebidos para evaluar la durabilidad a largo plazo y la reacción tardía de adiciones minerales como la ceniza volante.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="eda.html#cb16-1" tabindex="-1"></a>p4</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-9-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>Para la variable de respuesta “resistencia”, se observa un comportamiento mucho más homogéneo y balanceado, con un promedio de resistencia de <span class="math inline">\(35.8\text{ MPa}\)</span> y una desviación estándar de <span class="math inline">\(16.7\text{ MPa}\)</span>.</p>
<p>El 50% de los datos tienen una resistencia menor o igual a <span class="math inline">\(34.5\text{ MPa}\)</span>, mostrando una <strong>notable cercanía con el promedio de resistencia de las mezclas de concreto (<span class="math inline">\(35.8\text{ MPa}\)</span>)</strong>. En cuanto al rango intercuartílico, el <span class="math inline">\(25\%\)</span> de las mezclas con menor resistencia registran valores iguales o inferiores a <span class="math inline">\(23.7\text{ MPa}\)</span>, mientras que el <span class="math inline">\(75\%\)</span> de las muestras se sitúan por debajo de los <span class="math inline">\(46.1\text{ MPa}\)</span>. Los bigotes abarcan un rango que va desde un mínimo de <span class="math inline">\(2.3\text{ MPa}\)</span> (concreto de muy baja resistencia) hasta aproximadamente los <span class="math inline">\(80.0\text{ MPa}\)</span>. Se aprecian únicamente unos pocos <strong>valores atípicos superiores</strong> que alcanzan un máximo de <span class="math inline">\(82.6\text{ MPa}\)</span>.</p>
</div>
</div>
<div id="análisis-bivariado-relación-con-la-resistencia-del-concreto" class="section level2 hasAnchor" number="3.8">
<h2><span class="header-section-number">3.8</span> Análisis bivariado: relación con la resistencia del concreto<a href="eda.html#an%C3%A1lisis-bivariado-relaci%C3%B3n-con-la-resistencia-del-concreto" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="eda.html#cb17-1" tabindex="-1"></a>df_clean <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="eda.html#cb17-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> cemento, <span class="at">y =</span> resistencia)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="eda.html#cb17-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb17-4"><a href="eda.html#cb17-4" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb17-5"><a href="eda.html#cb17-5" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Dispersión entre el cemento y la resistencia del concreto&quot;</span>,</span>
<span id="cb17-6"><a href="eda.html#cb17-6" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Cemento (kg/m³)&quot;</span>,</span>
<span id="cb17-7"><a href="eda.html#cb17-7" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Resistencia (MPa)&quot;</span></span>
<span id="cb17-8"><a href="eda.html#cb17-8" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb17-9"><a href="eda.html#cb17-9" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-10-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>Existe una correlación positiva moderada-fuerte entre la cantidad de cemento y la resistencia del concreto. El diagrama de dispersión muestra que, en general, a medida que aumenta el cemento, también aumenta la resistencia. Por lo tanto, el cemento presenta una relación lineal importante con la variable respuesta.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="eda.html#cb18-1" tabindex="-1"></a>df_clean <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="eda.html#cb18-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> agua, <span class="at">y =</span> resistencia)) <span class="sc">+</span></span>
<span id="cb18-3"><a href="eda.html#cb18-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-4"><a href="eda.html#cb18-4" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-5"><a href="eda.html#cb18-5" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Dispersión entre el agua y la resistencia del concreto&quot;</span>,</span>
<span id="cb18-6"><a href="eda.html#cb18-6" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Agua (kg/m³)&quot;</span>,</span>
<span id="cb18-7"><a href="eda.html#cb18-7" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Resistencia (MPa)&quot;</span></span>
<span id="cb18-8"><a href="eda.html#cb18-8" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb18-9"><a href="eda.html#cb18-9" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-11-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>La cantidad de agua presenta una correlación negativa débil-moderada con la resistencia del concreto. El diagrama de dispersión muestra una tendencia en la que a mayor cantidad de agua en la mezcla, la resistencia tiende a disminuir. Por lo tanto, el agua parece tener una relación inversa con la resistencia del concreto.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="eda.html#cb19-1" tabindex="-1"></a>df_clean <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="eda.html#cb19-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> edad, <span class="at">y =</span> resistencia)) <span class="sc">+</span></span>
<span id="cb19-3"><a href="eda.html#cb19-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb19-4"><a href="eda.html#cb19-4" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb19-5"><a href="eda.html#cb19-5" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Dispersión entre el tiempo de curado y la resistencia del concreto&quot;</span>,</span>
<span id="cb19-6"><a href="eda.html#cb19-6" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Tiempo de curado (Días)&quot;</span>,</span>
<span id="cb19-7"><a href="eda.html#cb19-7" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Resistencia (MPa)&quot;</span></span>
<span id="cb19-8"><a href="eda.html#cb19-8" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb19-9"><a href="eda.html#cb19-9" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-12-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>La edad (tiempo de curado) presenta una correlación positiva con la resistencia del concreto. El diagrama de dispersión muestra que la resistencia aumenta rápidamente en los primeros días y luego el incremento se vuelve más lento a medida que pasa el tiempo. Por lo tanto, existe una relación notable entre ambas variables, aunque no es puramente lineal.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="eda.html#cb20-1" tabindex="-1"></a>df_clean <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="eda.html#cb20-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ceniza, <span class="at">y =</span> resistencia)) <span class="sc">+</span></span>
<span id="cb20-3"><a href="eda.html#cb20-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb20-4"><a href="eda.html#cb20-4" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb20-5"><a href="eda.html#cb20-5" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Dispersión entre la ceniza volante y la resistencia del concreto&quot;</span>,</span>
<span id="cb20-6"><a href="eda.html#cb20-6" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Ceniza volante (kg/m³)&quot;</span>,</span>
<span id="cb20-7"><a href="eda.html#cb20-7" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Resistencia (MPa)&quot;</span></span>
<span id="cb20-8"><a href="eda.html#cb20-8" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb20-9"><a href="eda.html#cb20-9" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-13-1.png" alt="" width="672" style="display: block; margin: auto;" /></p>
<p>La ceniza volante y la resistencia del concreto presentan una correlación lineal prácticamente nula. El diagrama de dispersión muestra una gran concentración de datos en cero y una amplia dispersión en las mezclas con ceniza, sin mostrar una tendencia lineal definida. Por lo tanto, la ceniza volante no parece tener una relación lineal directa con la resistencia del concreto.</p>
</div>
<div id="análisis-multivariado" class="section level2 hasAnchor" number="3.9">
<h2><span class="header-section-number">3.9</span> Análisis multivariado<a href="eda.html#an%C3%A1lisis-multivariado" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="eda.html#cb21-1" tabindex="-1"></a>df_clean <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="eda.html#cb21-2" tabindex="-1"></a>  <span class="fu">ggpairs</span>()</span></code></pre></div>
<p><img src="Proyecto_Final_Metodos_Estadisticos_files/figure-html/unnamed-chunk-14-1.png" alt="" width="1248" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="eda.html#cb22-1" tabindex="-1"></a>df_fe <span class="ot">&lt;-</span> df_clean <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="eda.html#cb22-2" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-3"><a href="eda.html#cb22-3" tabindex="-1"></a>    <span class="co">#  Razón Agua / Cementante(lo que endurece)</span></span>
<span id="cb22-4"><a href="eda.html#cb22-4" tabindex="-1"></a>    <span class="at">razon_agua_cementante =</span> agua <span class="sc">/</span> (cemento <span class="sc">+</span> ceniza),</span>
<span id="cb22-5"><a href="eda.html#cb22-5" tabindex="-1"></a></span>
<span id="cb22-6"><a href="eda.html#cb22-6" tabindex="-1"></a>    <span class="co">#  Porcentaje de Cemento sustituido por Ceniza</span></span>
<span id="cb22-7"><a href="eda.html#cb22-7" tabindex="-1"></a>    <span class="at">pct_ceniza =</span> (ceniza <span class="sc">/</span> (cemento <span class="sc">+</span> ceniza)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb22-8"><a href="eda.html#cb22-8" tabindex="-1"></a></span>
<span id="cb22-9"><a href="eda.html#cb22-9" tabindex="-1"></a>    <span class="co"># Etapas estándar de curado</span></span>
<span id="cb22-10"><a href="eda.html#cb22-10" tabindex="-1"></a>    <span class="at">etapa_curado =</span> <span class="fu">factor</span>(<span class="fu">case_when</span>(</span>
<span id="cb22-11"><a href="eda.html#cb22-11" tabindex="-1"></a>      edad <span class="sc">&lt;=</span> <span class="dv">7</span> <span class="sc">~</span> <span class="st">&quot;Temprano (&lt;= 7d)&quot;</span>,</span>
<span id="cb22-12"><a href="eda.html#cb22-12" tabindex="-1"></a>      edad <span class="sc">&gt;</span> <span class="dv">7</span> <span class="sc">&amp;</span> edad <span class="sc">&lt;=</span> <span class="dv">28</span> <span class="sc">~</span> <span class="st">&quot;estandar (14-28d)&quot;</span>,</span>
<span id="cb22-13"><a href="eda.html#cb22-13" tabindex="-1"></a>      edad <span class="sc">&gt;</span> <span class="dv">28</span> <span class="sc">~</span> <span class="st">&quot;Tardio (&gt; 28d)&quot;</span></span>
<span id="cb22-14"><a href="eda.html#cb22-14" tabindex="-1"></a>    ), <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Temprano (&lt;= 7d)&quot;</span>, <span class="st">&quot;estandar (14-28d)&quot;</span>, <span class="st">&quot;Tardio (&gt; 28d)&quot;</span>))</span>
<span id="cb22-15"><a href="eda.html#cb22-15" tabindex="-1"></a>  )</span></code></pre></div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["Proyecto_Final_Metodos_Estadisticos.pdf", "Proyecto_Final_Metodos_Estadisticos.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
